# Site settings
title: SP 1500-101 CDF for Election Event Logging
description: "NIST Special Publication: SP 1500-101 Election Event Logging Common Data Format Specification
Draft Version 1.0"
baseurl: "/ElectionEventLogging" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# GitHub information
org_name: usnistgov
repo_name: ElectionEventLogging

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /ElectionEventLogging/

host: 0.0.0.0
